version: '3.0'

services:
  auth:
    build: ./auth
    ports:
      - "8081:80"
    volumes:
      - ./auth:/var/www/html
    depends_on:
      - db

  properties:
    build: ./propers
    ports:
      - "8082:80"
    volumes:
      - ./propers:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: jiffy_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
